### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Only HTTP(S) protocols are supported

### ISSUE THREAD

**Issue by yellowgh0st** [vetherasset/vether-miner#1]
Happens when there's no protocol of WokeDyno URL specified inside .env 
and keeps spaming the output.

**Proposed solutions:**

1. Implement URL validator into wokeDyno.js
2. Hardcode the protocol like this
```
fetch(`https://${url}`).then(() => console.log(`Fetching ${url}.`)); 
```
3. Leave it as it is and predefine the default URL inside default dotenv as 
http://<your-dyno-url>:3000

4. Leve it as it is

**Solution**
 Specify the protocol when you set DYNO_URL

```
node:12086) UnhandledPromiseRejectionWarning: TypeError: Only HTTP(S) protocols are supported
    at getNodeRequestOptions (/home/augustin/vether-miner/node_modules/node-fetch/lib/index.js:1303:9)
    at /home/augustin/vether-miner/node_modules/node-fetch/lib/index.js:1404:19
    at new Promise (<anonymous>)
    at fetch (/home/augustin/vether-miner/node_modules/node-fetch/lib/index.js:1401:9)
    at Timeout._onTimeout (/home/augustin/vether-miner/wokeDyno.js:10:13)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
(node:12086) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 100)
```

**Comment by yellowgh0st** [comment]
4. might be enough as solution
Posting this issue because someone may find this useful.

**Comment by yellowgh0st** [comment]
1. Better to not implement it, to keep the script simple
2. Not a good solution without validator
